---
- name: Test Netgear M4300 Telnet connection
  hosts: switches
  connection: ready_1.unofficial_netgear_m4300.netgear_telnet
  gather_facts: false
  # Disable features not supported by network devices
  vars:
    ansible_python_interpreter: auto_silent
    ansible_connection: ready_1.unofficial_netgear_m4300.netgear_telnet

  tasks:
    - name: Test basic connection
      ansible.builtin.raw: help
      register: version_output

    - name: Display version output
      ansible.builtin.debug:
        msg: "{{ version_output.stdout }}"
